FROM node:alpine3.21 AS build
WORKDIR /frontend
COPY ./frontend/package.json ./
RUN npm install
COPY . .
RUN npm run build

# serve the app
FROM nginx:1.25-alpine
WORKDIR /usr/share/nginx/html
RUN rm -rf *
COPY --from=build /frontend/build .
EXPOSE 80
ENTRYPOINT [ "nginx", "-g", "daemon off;" ]