FROM node:alpine3.21 AS build

# Declare build time arguments
ARG REACT_APP_API_URL
ENV REACT_APP_API_URL=${REACT_APP_API_URL}

WORKDIR /frontend
COPY ./frontend/package*.json ./
RUN npm install
COPY ./frontend .
RUN npm run build

# serve the app
FROM nginx:1.25-alpine
WORKDIR /usr/share/nginx/html
RUN rm -rf *
COPY --from=build /frontend/build .
EXPOSE 80
ENTRYPOINT [ "nginx", "-g", "daemon off;" ]