version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/DockerFile
    container_name: gradsearch-job-insights-backend
    ports:
      - "${DB_PORT:-8080}:8080"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - NODE_ENV=${NODE_ENV:-production}
      - CHROMA_HOST=chroma
      - CHROMA_PORT=8000
    depends_on:
      - chroma
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: ./frontend/DockerFile
    container_name: gradsearch-job-insights-frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  chroma:
    image: chromadb/chroma
    container_name: chroma-server
    volumes:
      - chroma-data:/chroma/chroma
    ports:
      - "8000:8000"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  chroma-data:
