name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Backend Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./backend/DockerFile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/gradsearch-job-insights-backend:latest
          build-args: |
            DB_PORT=${{ secrets.DB_PORT }}
            MONGODB_URI=${{ secrets.MONGODB_URI }}
            NODE_ENV=production
            CHROMA_HOST="chroma-server"
            CHROMA_PORT=8000
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}

      - name: Build Frontend Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/gradsearch-job-insights-frontend:latest --build-arg REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }} -f ./frontend/DockerFile .
      - name: Push Frontend Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/gradsearch-job-insights-frontend:latest

  deploy:
    needs: build-and-push
    runs-on: self-hosted
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo chmod 666 /var/run/docker.sock
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Clean up existing containers
        run: |
          docker stop gradsearch-job-insights-backend gradsearch-job-insights-frontend chroma-server || true
          docker rm gradsearch-job-insights-backend gradsearch-job-insights-frontend chroma-server || true
          docker image prune -f

      - name: Create .env file for Docker Compose
        run: |
          echo "DB_PORT=${{ secrets.DB_PORT }}" > .env
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env
          echo "NODE_ENV=production" >> .env
          echo "CHROMA_HOST=chroma-server" >> .env 
          echo "CHROMA_PORT=8000" >> .env
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
          echo "REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}" >> .env

      - name: Pull Docker Images
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/gradsearch-job-insights-backend:latest
          docker pull ${{ secrets.DOCKER_USERNAME }}/gradsearch-job-insights-frontend:latest
          docker pull chromadb/chroma

      - name: Create Docker Network
        run: docker network create gradsearch-network || true

      - name: Run Docker Containers
        run: |
          docker volume create chroma-data
          docker run -d --name chroma-server --network gradsearch-network -p 8000:8000 -v chroma-data:/chroma/chroma chromadb/chroma

          docker run -d --name gradsearch-job-insights-backend --network gradsearch-network -p ${DB_PORT:-8080}:8080 -e MONGODB_URI="${{ secrets.MONGODB_URI }}" -e OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}" -e NODE_ENV=production -e CHROMA_HOST="chroma-server" -e CHROMA_PORT=8000 ${{ secrets.DOCKER_USERNAME }}/gradsearch-job-insights-backend:latest

          docker run -d --name gradsearch-job-insights-frontend --network gradsearch-network -p 3000:80 ${{ secrets.DOCKER_USERNAME }}/gradsearch-job-insights-frontend:latest

      # - name: Add Node and Populate Chromadb
      #   run: |
      #     sudo apt install nodejs
      #     sudo apt install npm
      #     cd ./backend
      #     npm install
      #     cd ..
      #     node ./backend/scripts/populateChroma.js

      - name: Cleanup
        run: |
          # Remove unused images, containers, networks, and volumes
          docker system prune -f
          # Remove old images to prevent disk space issues
          docker image prune -a -f --filter "until=24h"
